//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSize
    {
        public int SizeId { get; set; }
        public string Description { get; set; }
        public string Dimensions { get; set; }
        public Nullable<decimal> Weight { get; set; }
    }
}
